// <auto-generated />
using System;
using App_Gym.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App_Gym.Migrations
{
    [DbContext(typeof(App_GymDabataseContext))]
    partial class App_GymDabataseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App_Gym.Models.Actividad", b =>
                {
                    b.Property<int>("idActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantTurnos")
                        .HasColumnType("int");

                    b.Property<int>("cantTurnosDisponibles")
                        .HasColumnType("int");

                    b.Property<DateTime>("horario")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("profesorid")
                        .HasColumnType("int");

                    b.HasKey("idActividad");

                    b.HasIndex("profesorid");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("App_Gym.Models.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("App_Gym.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActividadidActividad")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Socioid")
                        .HasColumnType("int");

                    b.HasKey("IdTurno");

                    b.HasIndex("ActividadidActividad");

                    b.HasIndex("Socioid");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("App_Gym.Models.Profesor", b =>
                {
                    b.HasBaseType("App_Gym.Models.Persona");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("App_Gym.Models.Socio", b =>
                {
                    b.HasBaseType("App_Gym.Models.Persona");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("App_Gym.Models.Actividad", b =>
                {
                    b.HasOne("App_Gym.Models.Profesor", "profesor")
                        .WithMany()
                        .HasForeignKey("profesorid");
                });

            modelBuilder.Entity("App_Gym.Models.Turno", b =>
                {
                    b.HasOne("App_Gym.Models.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadidActividad");

                    b.HasOne("App_Gym.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("Socioid");
                });
#pragma warning restore 612, 618
        }
    }
}
